
server:
  port: 9090
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  application:
    name: 个性化问答数据平台
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: root
    password: Q
    druid:
      initial-size: 2
      db-type: com.alibaba.druid.pool.DruidDataSource
      min-idle: 2
      max-wait: 60000
  servlet:
    multipart:
      max-file-size: 512MB  # Max file size
      max-request-size: 512MB #Max request size 默认10M
  redis:
    host: 
    port: 6379
    password: 
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  elasticsearch:
    rest:
      username: elastic
      password: 123456
      connection-timeout: 1000
      uris: http://192.168.109.129:9200
  data:
    mongodb:
      uri: 
  profiles:
    active: dev
mybatis-plus:
  type-aliases-package: com.personalize.personalizeqa.entity
logging:
  level:
    com.personalize.personalizeqa: debug
personalize:
  nginx:
    ip: localhost
    port: 10000
  file:
    type: ALI
    local:
      uri-prefix: http://127.0.0.1:10000
      bucket-name: dataset-files
      endpoint: C:\IT\Project\QA\uploadFiles
    ali:
      bucket-name: personlized-loan
      endpoint: 
      access-key-id: 
      access-key-secret: 
  database:
    isBlockAttack: false  # 是否启用 攻击 SQL 阻断解析器
id-generator:
  machine-code: 1  # id生成器机器掩码
